
const videoSources =  {
    'Jump Squat': require('../assets/animation/man/Man_Jump_Squat.mp4'),
    'Bicycle Crunch': require('../assets/animation/man/Man_Bicycle_Crunch.mp4'),
    'Bicyle Crunches': require('../assets/animation/man/Man_Bicyle_Crunches.mp4'),
    'Calf Raises': require('../assets/animation/man/Man_Calf_Raises.mp4'),
    'Cossack Squat': require('../assets/animation/man/Man_Cossack_Squat.mp4'),
    'Finger Wave': require('../assets/animation/man/Man_Finger_Wave.mp4'),
    'Forward Lunge': require('../assets/animation/man/Man_Forward_Lunge.mp4'),
    'Incline Push_Up': require('../assets/animation/man/Man_Incline_Push_Up.mp4'),
    'Kneeling Diamond_Push_Ups': require('../assets/animation/man/Man_Kneeling_Diamond_Push_Ups.mp4'),
    'Push-Ups': require('../assets/animation/man/Man_Push_Ups.mp4'),
    'Reverse Crunch': require('../assets/animation/man/Man_Reverse_Crunch.mp4'),
    'Rope Assisted Leg Raise': require('../assets/animation/man/Man_Rope_Assisted_Leg_Raise.mp4'),
    'Side Crunch': require('../assets/animation/man/Man_Side_Crunch.mp4'),
    'Single Leg Squat': require('../assets/animation/man/Man_Single_Leg_Squat.mp4'),
    'Single Leg Squat_Reach': require('../assets/animation/man/Man_Single_Leg_Squat_Reach.mp4'),
    'Split Squat': require('../assets/animation/man/Man_Split_Squat.mp4'),
    'Squats': require('../assets/animation/man/Man_Squats.mp4'),
    'Standing Leg Raise': require('../assets/animation/man/Man_Standing_Leg_Raise.mp4'),
    'Standing Trunk Twist': require('../assets/animation/man/Man_Standing_Trunk_Twist.mp4'),
    'Straight Arm Elevated Dip': require('../assets/animation/man/Man_Straight_Arm_Elevated_Dip.mp4'),
    'Tricep Dip': require('../assets/animation/man/Man_Tricep_Dip.mp4'),
    'Wall Pshups': require('../assets/animation/man/Man_Wall_Pshups.mp4'),
    'Forward Lunges': require('../assets/animation/lady/Lady_Forward_Lunges.mp4'),
    'Bent-Knee Sit-Ups': require('../assets/animation/lady/Lady_Bent_Knee_Sit_Ups.mp4'),
    'Bicycle Crunch': require('../assets/animation/lady/Lady_Bicycle_Crunch.mp4'),
    'Calf Raises': require('../assets/animation/lady/Lady_Calf_Raises.mp4'),
    'Chest Lift': require('../assets/animation/lady/Lady_Chest_Lift.mp4'),
    'Cossack Squat': require('../assets/animation/lady/Lady_Cossack_Squat.mp4'),
    'High Knees Exercise': require('../assets/animation/lady/Lady_High_Knees_Exercise.mp4'),
    'Plank': require('../assets/animation/lady/Lady_Plank.mp4'),
    'Push-Ups': require('../assets/animation/lady/Lady_Push_Ups.mp4'),
    'Side plank': require('../assets/animation/lady/Lady_Side_pLank.mp4'),
    'Reverse Crunch': require('../assets/animation/lady/Lady_Reverse_Crunch.mp4'),
    'Push-up on Knees': require('../assets/animation/lady/Lady_Push-up_on_knees.mp4'),
    'Side Leg Lift': require('../assets/animation/lady/Lady_Side_Leg_Lift.mp4'),
    'Side Squat': require('../assets/animation/lady/Lady_Side_Squat.mp4'),
    'Split Squat': require('../assets/animation/lady/Lady_Split_Squat.mp4'),
    'Squat': require('../assets/animation/lady/Lady_Squat.mp4'),
    'Standing Knee Lift': require('../assets/animation/lady/Lady_Standing_Knee_Lift.mp4'),
    'Straight Leg Raise': require('../assets/animation/lady/Lady_Straight_Leg_Raise.mp4'),
    'Toe Walking': require('../assets/animation/lady/Lady_Toe_Walking.mp4'),
    'Twisting Crunch': require('../assets/animation/lady/Lady_Twisting_Crunch.mp4'),
  };
  
export default videoSources;